language: python
python:
  - "2.7"
  - "3.2"
# command to install dependencies
install:
    - pip install coveralls
    - pip install termcolor
# command to run tests
script: make test
after_success:
  coveralls
